### ISSUE TITLE
doors doesn’t work on coraptions

### ISSUE THREAD

**Issue by BlahajTheShark14** [ValkyrienSkies/Create-Interactive-Issues#112] opened 2024-11-25 20:47 UTC
e.g.: like on an elevator, or on a train. Idk why is this mod abandoned. If the bigger issues would be fixed, it would became a great mod!

**Comment by xiewuzhiying** [comment] 2024-12-02 18:37
Fixed in development version

**Comment by BlahajTheShark14** [comment] 2024-12-03 12:45
oh thats cool, when it will came out? (approx)

**Comment by BlahajTheShark14** [comment] 2024-12-03 13:00
like, it will be ready in this month?

**Comment by blockninja124** [comment] 2024-12-03 21:39
Closing as I think this is a duplicate of https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/97. As to when the update will come out, I don’t know. Chances are it’ll be within a month or so?

**Closed by blockninja124** 2024-12-03 21:39 UTC
Labels: bug
