### ISSUE TITLE
Create interactive Fabric Crash while loading word

### ISSUE THREAD

**Issue by unjuannito** [ValkyrienSkies/Create-Interactive-Issues#86] opened 2024-05-18 14:46 UTC
With the last version of Create Fabric, Create Interactive and Valkiyries skyes the game crash while loading a world
The log:
[latest.log](https://github.com/ValkyrienSkies/Create-Interactive-Issues/files/15365713/latest.log)

**Comment by CheetahCyberBoi** [comment] 2024-05-27 21:16
Having this too.

**Comment by Kitieshka** [comment] 2024-06-03 08:22
me too

**Comment by blockninja124** [comment] 2024-12-03 21:36
This this is a duplicate of https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/89

**Closed** 2024-12-03 21:36 UTC
Labels: real :flushed:, duplicate, bug
