### ISSUE TITLE
fabric1.19.2server.log

### ISSUE THREAD

**Issue by Yummy-cookie** [ValkyrienSkies/Create-Interactive-Issues#92] opened 2024-07-19 09:14 UTC
---- Minecraft Crash Report ----
// Oops.

Time: 2024-07-19 09:08:39
Description: Exception in server tick loop

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.trains.entity.Train failed
	at com.simibubi.create.content.trains.GlobalRailwayManager.loadTrackData(GlobalRailwayManager.java:94)
	at com.simibubi.create.content.trains.GlobalRailwayManager.levelLoaded(GlobalRailwayManager.java:83)
	at com.simibubi.create.foundation.events.CommonEvents.onLoadWorld(CommonEvents.java:178)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34)
	at net.minecraft.server.MinecraftServer.redirect$chf000$fabric-lifecycle-events-v1$onLoadWorld(MinecraftServer.java:10329)
	at net.minecraft.server.MinecraftServer.createLevels(MinecraftServer.java:351)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:315)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:172)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:257)
	at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.trains.entity.Train failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base@21.0.3/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 15 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [create_interactive.mixins.json:MixinTrain from mod create_interactive] from phase [DEFAULT] in config [create_interactive.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Overwrite method findCollidingTrain in create_interactive.mixins.json:MixinTrain from mod create_interactive was not located in the target class com.simibubi.create.content.trains.entity.Train. Using refmap create_interactive-fabric-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.15.0-113-generic
	Java Version: 21.0.3, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 22320610256 bytes (21286 MiB) / 23622320128 bytes (22528 MiB) up to 24696061952 bytes (23552 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
	Identifier: Intel64 Family 6 Model 62 Stepping 4
	Microarchitecture: Ivy Bridge (Server)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 12
	Graphics card #0 name: GD 5446
	Graphics card #0 vendor: Cirrus Logic (0x1013)
	Graphics card #0 VRAM (MB): 32.00
	Graphics card #0 deviceId: 0x00b8
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: RAM
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: RAM
	Virtual memory max (MB): 12013.71
	Virtual memory used (MB): 3421.61
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms22G -Xmx23G
	Fabric Mods: 
		ad_astra: Ad Astra 1.12.7
		ad_astra_giselle_addon: Ad Astra: Giselle Addon 1.21
		adorn: Adorn 3.9.1+1.19.2
		antixray: AntiXray 1.3.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		appleskin: AppleSkin 2.5.1+mc1.19
		architectury: Architectury 6.6.92
		balm-fabric: Balm 4.6.0
		bclib: BCLib 2.1.8
		better-fabric-console: Better Fabric Console 1.1.2
			adventure-platform-fabric: adventure-platform-fabric 5.5.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.11.0
				net_kyori_adventure-key: adventure-key 4.11.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.2
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			net_fabricmc_mapping-io: mapping-io 0.3.0
			net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.11.0
			org_fusesource_jansi_jansi: jansi 2.4.0
			org_jline_jline: jline 3.21.0
			org_jline_jline-terminal-jansi: jline-terminal-jansi 3.21.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bettercombat: Better Combat 1.7.1+1.19
		betterend: Better End 2.1.7
		betternether: Better Nether 7.1.5
		betterthanmending: BetterThanMending 1.3.0
		botarium: Botarium 1.9.2
		byg: Oh The Biomes You'll Go 2.0.1.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		carpet: Carpet Mod 1.4.84
		carryon: Carry On 2.1.2.23
		chunky: Chunky 1.3.38
		cloth-config: Cloth Config v8 8.3.115
			cloth-basic-math: cloth-basic-math 0.6.1
		computercraft: CC: Restitched 1.101.2
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		copycats: Create: Copycats+ 2.0.2+mc.1.19.2-fabric
		corgilib: CorgiLib 1.0.0.34
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		create: Create 0.5.1-f-build.1416+mc1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Porting Lib Tags 3.0
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib_accessors: Porting Lib Accessors 2.1.1305+1.19.2
			porting_lib_base: Porting Lib Base 2.1.1305+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1305+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1305+1.19.2
				porting_lib_models: Porting Lib Models 2.1.1305+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			porting_lib_entity: Porting Lib Entity 2.1.1305+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.1305+1.19.2
			porting_lib_extensions: Porting Lib Extensions 2.1.1305+1.19.2
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1305+1.19.2
			porting_lib_networking: Porting Lib Networking 2.1.1305+1.19.2
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1305+1.19.2
			porting_lib_transfer: Porting Lib Transfer 2.1.1305+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.1305+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.58-MC1.19.2
		create_interactive: Create: Interactive 1.0.1-beta.3
		create_jetpack: Create Jetpack 3.5.0
			flightlib: Flight Lib 1.2.0
		create_new_age: Create: New Age 1.0.1
			org_joml_joml: joml 1.10.5
		createaddition: Create Crafts & Additions 1.2.3
			team_reborn_energy: Energy 2.3.0
		createdeco: Create Deco 1.3.3-1.19.2
		ctov: ChoiceTheorem's Overhauled Village 3.2.6c
		dark-matter: Dark Matter 3.1.0-1.19.2
			dark-matter-base: Dark Matter Base 3.1.0-1.19.2
			dark-matter-content: Dark Matter Content 3.1.0-1.19.2
			dark-matter-crash-handler: Dark Matter Crash Handler 3.1.0-1.19.2
			dark-matter-danger: Dark Matter Danger 3.1.0-1.19.2
			dark-matter-enums: Dark Matter Enums 3.1.0-1.19.2
			dark-matter-glitter: Dark Matter Glitter 3.1.0-1.19.2
			dark-matter-minecraft: Dark Matter Minecraft 3.1.0-1.19.2
			dark-matter-mirage: Dark Matter Mirage 3.1.0-1.19.2
			dark-matter-recipe-book: Dark Matter Recipe Book 3.1.0-1.19.2
		deathlog: DeathLog 0.2.11+1.19
		design_decor: Create: Design n' Decor 0.4_fabric+1.19.2
		dungeons_arise: When Dungeons Arise 2.1.56
		easyauth: Easy Authentication Mod 3.0.19
			at_favre_lib_bcrypt: bcrypt 0.9.0
			at_favre_lib_bytes: bytes 1.5.0
			com_mysql_mysql-connector-j: mysql-connector-j 8.0.33
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			net_java_dev_jna_jna: jna 5.12.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.7.2
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.7.2
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.7.2
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		editsign: EditSign 2.6.0
		effortless: Effortless Structure 3.0.0
		enhancedcelestials: Enhanced Celestials 2.1.0.6
		essential_commands: Essential Commands 0.33.2-mc1.19.2
			ec-core: Essential Commands Core 1.3.0-mc1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 1.33
			playerabilitylib: Pal 1.6.0
		fabric-api: Fabric API 0.77.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+ee641e7390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 5.0.3
		forgeconfigapiport: Forge Config API Port 4.2.11
		ftblibrary: FTB Library 1902.4.1-build.236
		ftbultimine: FTB Ultimine 1902.4.1-build.90
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		hookshot: Hookshot 26.0
		improvedmobs: Improved Mobs 1.19-1.11.0
		infwithmend: Infinity with Mending 1.0.2
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 11.6.0.1024
		lazydfu: LazyDFU 0.1.3
		ledger: Ledger 1.2.5
		lithium: Lithium 0.11.1
		mca: Minecraft Comes Alive 7.5.14+1.19.2
		mcqq: MC_QQ_Fabric 2.7.2
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.19.2
		minemenufabric: MineMenuFabric 6.3.0-1.19.2
		modernfix: ModernFix 5.18.0+mc1.19.2
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		opaccreatesupport: OPAC Create Mod Support 1.6.0
		openpartiesandclaims: Open Parties and Claims 0.23.1
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		perfectaccuracy: Perfect Accuracy 1.3
		player-animator: Player Animator 1.0.2
		railways: Create: Steam 'n' Rails 1.6.4+fabric-mc1.19.2
			mm: Manningham Mills 2.3
		resourcefulconfig: Resourcefulconfig 1.0.20
		resourcefullib: Resourceful Lib 1.1.24
		smoothboot: Smooth Boot 1.19-1.7.1
		sophisticatedbackpacks: Sophisticated Backpacks 3.19.5+mc1.19.2-SNAPSHOT-build.103
			porting_lib_common: Porting Lib Common 2.1.1305+1.19.2
			porting_lib_loot: Porting Lib Loot 2.1.1305+1.19.2
			porting_lib_model_loader: Porting Lib Model Loader 2.1.1305+1.19.2
		sophisticatedcore: Sophisticated Core 0.5.109+mc1.19.2-SNAPSHOT-build.103
		spark: spark 1.10.37
		starlight: Starlight 1.1.1+fabric.ae22326
		talkbubbles: Talk Bubbles 1.0.4
		tenshilib: TenshiLib 1.19.2-1.6.15
		terrablender: TerraBlender 2.0.1.166
		valkyrienskies: Valkyrien Skies 2 2.1.2-beta.1
		vmp: Very Many Players 0.2.0+beta.7.30
		voicechat: Simple Voice Chat 1.19.2-2.5.19
		vs_clockwork: Clockwork: Create x Valkyrien Skies 1.19.2-0.1.13-fabric-4621aeec07
		vs_eureka: VS Eureka Mod 1.5.1-beta.2
		waystones: Waystones 11.4.2
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		xaerominimap: Xaero's Minimap 24.2.0
		xaeroworldmap: Xaero's World Map 1.38.8
	Server Running: true
	Player Count: 0 / 114154; []
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by blockninja124** [comment] 2024-12-03 20:59
Can you try to provide more information on what you were doing, etc? Also try to narrow the issue down to a smaller, or preferably only one, incompatible mod.

**Comment by blockninja124** [comment] 2024-12-03 21:35
I think this is a duplicate of https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/86

**Closed by blockninja124** 2024-12-03 21:35 UTC
Labels: Needs more info, bug
